export const genres = [
    "Adventure",
    "Action",
    "Arcade",
    "Board game",
    "Driving/Pilot sim",
    "Dungeon Crawler",
    "Fighting",
    "MMO",
    "MOBA",
    "Party",
    "Platformer",
    "Playable Cinema",
    "Puzzle",
    "Racing",
    "RPG",
    "RTS",
    "Shooter",
    "Sports",
    "Versus",
  ];

  export const cameras = [
    "cinematic",
    "first-person",
    "horizontal scroll",
    "isometric",
    "manual move",
    "single-screen/arena",
    "third-person",
    "top-down",
    "veritcal scroll",
  ];

const others ={  
  traversal: [
    "locked scroll / no going back",
    "on-rails/push",
    "open-world",
    "wrap-around/teleport/infinite",
  ],
  inputScheme: [
    "1D linear analog",
    "1D linear grid",
    "2D analog",
    "2D grid",
    "3D free-roam",
    "3D focused point",
    "auto/command",
    "directional/momentum",
    "input timing",
    "object manipulation",
    "pseudo-3D movement",
    "simulation/emulation",
  ],
  theme: [
    "animal",
    "chill",
    "competitive",
    "cute",
    "cyberpunk",
    "dark _____ ",
    "dystopian",
    "exaggerated/fantastical",
    "extreme sports",
    "food",
    "historic",
    "mash-up",
    "mech",
    "medieval fantasy",
    "military",
    "music",
    "mythology",
    "neon",
    "none",
    "nonsense",
    "organized sports",
    "popular license",
    "post-apocalyptic",
    "pre-historic",
    "rage",
    "realistic",
    "sci-fi",
    "simple",
    "space",
    "steampunk",
    "technological",
    "trippy",
    "violence and gore",
  ],
  mechanics: [
    "aim/fire",
    "combat",
    "competitive ranking",
    "enemy waves",
    "exploration",
    "item collection",
    "leveling",
    "maneuver/navigation",
    "procedural generation",
    "puzzle-solving",
    "resource management",
    "sorting",
    "trivia",
  ]
};